#!/bin/sh

set -x
export MAKEFLAGS=-j` nproc`
export CFLAGS="-s"
export CXXFLAGS="-s"

GCC_VERSION=8.2.0
export ROOTDIR=/mnt/tmp-data/sebastian/abanu-toolchain
export PREFIX="$ROOTDIR/opt/gcc-$GCC_VERSION"

# bootstrap binutils

cd $ROOTDIR
mkdir -p build-binutils
cd build-binutils
../binutils-gdb/configure --prefix="$PREFIX" --disable-nls --disable-werror
make
make install

# bootstrap gcc

cd $ROOTDIR
mkdir -p build-gcc
cd build-gcc
../gcc/configure --prefix="$PREFIX" --disable-nls --enable-languages=c,c++
make
make install-strip

export PATH="$ROOTDIR/opt/gcc-$GCC_VERSION-cross/bin:$PATH"

export PREFIX="$ROOTDIR/opt/gcc-$GCC_VERSION-cross"
export TARGET=i686-elf
export PATH="$PREFIX/bin:$PATH"

# build cross binutils

cd $ROOTDIR
mkdir build-binutils-cross
cd build-binutils-cross
../binutils-gdb/configure --target=$TARGET --prefix="$PREFIX" --with-sysroot --disable-nls --disable-werror
make
make install

echo $PATH

# build cross gcc

cd $ROOTDIR
# The $PREFIX/bin dir _must_ be in the PATH. We did that above.
which -- $TARGET-as || echo $TARGET-as is not in the PATH
mkdir -p build-gcc-cross
cd build-gcc-cross
../gcc/configure --target=$TARGET --prefix="$PREFIX" --disable-nls --enable-languages=c,c++ --without-headers
make all-gcc -j13
make all-target-libgcc
make install-strip-gcc
make install-strip-target-libgcc

cd $ROOTDIR
#tar cf - opt | pigz > gcc-bin.tar.gz
